// Main
export const SET_MAXIMIZED = 'SET_MAXIMIZED';
export const SET_FULLSCREEN = 'SET_FULLSCREEN';
export const LOGOUT = 'LOGOUT';
export const TOOLTIP = 'TOOLTIP';
export const UPDATE_RECENT_ASSIGNEES = 'UPDATE_RECENT_ASSIGNEES';
export const CONTEXT_MENU = 'CONTEXT_MENU';
export const SUCCESS_GRADIENT = 'SUCCESS_GRADIENT';

// Navigation
export const NAVIGATION_URL = 'NAVIGATION_URL';
export const NAVIGATION_SET = 'NAVIGATION_SET';
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';
export const NAVIGATION_SAVE_STATE = 'NAVIGATION_SAVE_STATE';
export const NAVIGATION_SET_COUNTER = 'NAVIGATION_SET_COUNTER';
export const NAVIGATION_TOGGLE_LOCK = 'NAVIGATION_TOGGLE_LOCK';
export const NAVIGATION_MODAL = 'NAVIGATION_MODAL';

// Search
export const SEARCH = 'SEARCH';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

// Preview
export const PREVIEW_LOADING = 'PREVIEW_LOADING';
export const PREVIEW = 'PREVIEW';
