
// NAVIGATION
export const SLIDER_CHANGE = 'SLIDER_CHANGE';
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';
export const SET_ACTION_BUTTONS = 'SET_ACTION_BUTTONS';

// MODALS
export const SHOW_MODAL = 'SHOW_MODAL';

export const SHOW_LOADER = 'SHOW_LOADER';
