export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN'
export const TOGGLE_SEARCHING = 'TOGGLE_SEARCHING'
export const SET_STATUS = 'SET_STATUS'

export const LOAD_MODAL = 'LOAD_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const LOGOUT = 'LOGOUT'

export const API_REQUEST = 'API_REQUEST'
export const API_SUCCESS = 'API_SUCCESS'
export const API_ERROR = 'API_ERROR'

export const SOCKET_MESSAGE = 'SOCKET_MESSAGE'

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
export const UPDATE_LAST_SENT_TIME = 'UPDATE_LAST_SENT_TIME'