// Main
export const SET_MAXIMIZED = 'SET_MAXIMIZED';
export const SET_FULLSCREEN = 'SET_FULLSCREEN';
export const TOOLTIP = 'TOOLTIP';
export const CONTEXT_MENU = 'CONTEXT_MENU';
export const SUCCESS_GRADIENT = 'SUCCESS_GRADIENT';

// Invitation
export const INVITATION_SET_ORGANIZATION = 'INVITATION_SET_ORGANIZATION';
export const INVITATION_CLEAR = 'INVITATION_CLEAR';

// Navigation
export const NAVIGATION_URL = 'NAVIGATION_URL';
export const NAVIGATION_SET = 'NAVIGATION_SET';
export const NAVIGATION_PUSH = 'NAVIGATION_PUSH';
export const NAVIGATION_POP = 'NAVIGATION_POP';
export const NAVIGATION_SAVE_STATE = 'NAVIGATION_SAVE_STATE';
export const NAVIGATION_TOGGLE_LOCK = 'NAVIGATION_TOGGLE_LOCK';
export const NAVIGATION_SET_ON_TOP = 'NAVIGATION_SET_ON_TOP';
export const NAVIGATION_MODAL = 'NAVIGATION_MODAL';
